version: "2"
services:
  geolocation:
    build: ./services/geolocation
    volumes:
      - ./services/geolocation:/geolocation
    links:
      - mongo
  portal:
    build: ./services/portal
    volumes:
      - ./services/portal:/portal
      - ./data/drive/storage:/portal/storage
    links:
      - mongo
  gateway:
    build: nginx
    volumes:
      - ./data/log/nginx:/var/log/nginx/
    links:
      - portal
    ports:
      - "80:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/db/mongo:/data/db"
