version: "2"
services:
  catalog:
    build: ./services/catalog
    volumes:
      - ./services/catalog:/catalog
      - ./data/log/pm2:/var/log/pm2
    links:
      - mongo
  geolocation:
    build: ./services/geolocation
    volumes:
      - ./services/geolocation:/geolocation
      - ./data/log/pm2:/var/log/pm2
    links:
      - mongo
  portal:
    depends_on:
       - mysql
    build: ./services/portal
    volumes:
      - ./services/portal:/portal
      - ./data/drive/storage:/portal/storage
      - ./data/log/pm2:/var/log/pm2
    links:
      - mongo
      - mysql
  gateway:
    build: nginx
    volumes:
      - ./data/log/nginx:/var/log/nginx/
    links:
      - portal
      - geolocation
      - catalog
    ports:
      - "80:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/db/mongo:/data/db"
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./data/db/mysql:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: pass1word
       MYSQL_DATABASE: came
       MYSQL_USER: came
       MYSQL_PASSWORD: came
